#!/bin/bash

set -o errexit
set -o nounset
set -o xtrace

cd "${0%/*}"
echo "$(date -Is) Loading environment"
source credentials.env
source env/bin/activate

echo "$(date -Is) Starting check.py"
python check.py
echo "$(date -Is) Finished check.py"
